#define PLUS                            1
#define SUB                             2
#define MULT                            3
#define DIV                             4
#define MOD                             5
#define VAL                             6
#define LPAREN                          7
#define RPAREN                          8
#define END                             9
#define H                              10
#define I                              11
