#define PLUS                            1
#define SUB                             2
#define MULT                            3
#define DIV                             4
#define MOD                             5
#define END                             6
#define IDENT                           7
#define EQ                              8
#define VAL                             9
#define LPAREN                         10
#define RPAREN                         11
